"use client";

import React, { useState } from 'react';
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import SearchInputGroup from "@/components/SearchInputGroup";
import { youtubeApi } from "@/lib/api/endpoints";
import { CaptionTrack } from "@/types/video";
import { toast } from "@/lib/utils/toast";
import { extractVideoId } from "@/lib/utils/youtube";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { AlertCircle, FileText } from "lucide-react";

export default function CaptionsPage() {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [captionData, setCaptionData] = useState<CaptionTrack[]>([]);

  const handleSearch = async () => {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);

    try {
      const videoId = extractVideoId(query);
      if (!videoId) {
        setError("Invalid video URL or ID. Please enter a valid YouTube video link.");
        toast.error("Invalid video URL or ID");
        setLoading(false);
        return;
      }
      const data = await youtubeApi.getCaptions(videoId);
      setCaptionData(data.captions);
    } catch (e: any) {
      const msg = e.status === 401 ? "Authorization required. Please authenticate with Google." :
                  e.status === 404 ? "Resource not found" :
                  e.status === 429 ? "API Quota exhausted" :
                  "Failed to fetch data";
      setError(msg);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout
      title="Caption Extractor"
      description="Extract structured data directly from YouTube Data API v3."
    >
      <div className="space-y-10">
        <SearchInputGroup
          value={query}
          onChange={setQuery}
          onSearch={handleSearch}
          loading={loading}
          error={!!error}
          placeholder="Enter video URL or ID (e.g., dQw4w9WgXcQ)"
        />

        {error && (
          <Alert variant="destructive" className="rounded-xl border-0 bg-destructive/10 text-destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        <div className="space-y-6">
          {captionData.length > 0 && (
            <div className="space-y-3">
              {captionData.map((track) => (
                <div key={track.languageCode} className="flex items-center justify-between p-4 bg-card rounded-xl">
                  <div className="flex items-center gap-3">
                    <FileText className="h-5 w-5 text-primary" />
                    <span className="font-medium">{track.languageName}</span>
                    {track.isAutoGenerated && <Badge variant="secondary" className="text-[10px] uppercase">Auto</Badge>}
                  </div>
                  <span className="text-xs text-muted-foreground font-mono">{track.languageCode}</span>
                </div>
              ))}
            </div>
          )}

          {captionData.length === 0 && !loading && !error && (
            <div className="py-20 text-center bg-card rounded-2xl">
              <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4 opacity-20" />
              <p className="text-muted-foreground">No data extracted yet. Enter a valid video ID to begin.</p>
            </div>
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
